_BASE_: iu_debug_base.yml

start_gen: 1
gpu: 0

# ${root}/checkpoints', args.expe_name
expe_name: con_3_debug
N: 3

cnn_epoch: 8
learning_rate_cnn: 0.0000
alpha: 0.8
beta: 0.999
learning_rate: 0.0005
lr_decay: 10
learning_rate_decay_every: 10

# pretrained:
num_epochs: 100
batch_size: 32
clip: 5


