_BASE_: mimic_4last_base.yml

gpu: 5
start_gen: 1

# ${root}/checkpoints', args.expe_name
expe_name: con2_4last
N: 2

#cnn_epoch: 8
#learning_rate_cnn: 0.00001

alpha: 0.8
beta: 0.999
learning_rate: 0.0005

# pretrained:
num_epochs: 30
batch_size: 32
clip: 5

lr_decay: 10
learning_rate_decay_every: 10