_BASE_: mimic_sim_base.yml

gpu: 4
start_gen: 1

# ${root}/checkpoints', args.expe_name
expe_name: con1_similar
N: 1

learning_rate: 0.0005

# pretrained:
num_epochs: 50
batch_size: 64
clip: 5

lr_decay: 10
learning_rate_decay_every: 10
