_BASE_: mimic_base.yml

gpu: 7
start_gen: 1

# ${root}/checkpoints', args.expe_name
expe_name: con_2_not_mutlti_similar_sup
N: 2

cnn_epoch: 5
learning_rate_cnn: 0.00001

alpha: 0.8
beta: 0.999
learning_rate: 0.0005

# pretrained:
num_epochs: 100
batch_size: 32
clip: 5

lr_decay: 10
learning_rate_decay_every: 10
