_BASE_: mimic_sim_base.yml

gpu: 6
start_gen: 1

# ${root}/checkpoints', args.expe_name
expe_name: con3_similar
N: 3

learning_rate: 0.0005

# pretrained:
num_epochs: 50
batch_size: 32
clip: 5

lr_decay: 10
learning_rate_decay_every: 10
