_BASE_: mimic_sim_base.yml

gpu: 7
start_gen: 1

# ${root}/checkpoints', args.expe_name
expe_name: con5_similar
N: 5

learning_rate: 0.0005

# pretrained:
num_epochs: 50
batch_size: 16
clip: 5

lr_decay: 10
learning_rate_decay_every: 10
